name: Release Tauri App

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.bun/install/cache
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/bun.lockb') }}
      - name: Install dependencies
        run: bun install
      - name: Build Tauri app
        run: bun run tauri build
      - name: Rename artifacts
        run: |
          VERSION=${GITHUB_REF_NAME} # e.g. v1.0.0
          OUTDIR=src-tauri/target/release/bundle
          mkdir -p dist
          for f in $(find $OUTDIR -type f); do
            fname=$(basename $f)
            cp "$f" "dist/${fname%%.*}-${VERSION}-${{ matrix.platform }}.${fname##*.}"
          done
      - uses: actions/upload-artifact@v3
        with:
          name: tauri-${{ matrix.platform }}-${{ github.ref_name }}
          path: dist/*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: dist

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: dist/**/*
